cookie:
  expiry_days: 30
  key: my_secret_key
  name: my_cookie_name
credentials:
  usernames:
    jbastruz:
      email: none
      logged_in: false
      name: Jean-Baptiste
      password: *********
preauthorized:
  emails: []
