cookie:
  expiry_days: 30
  key: my_secret_key
  name: my_cookie_name
credentials:
  usernames:
    jbastruz:
      email: none
      logged_in: false
      name: Jean-Baptiste
      password: Jbastruz74940
    jmastruz:
      email: none
      logged_in: false
      name: Jean-Marc
      password: JMA260364
    mimoune:
      email: none
      logged_in: false
      name: Mimoune
      password: 260496
    iastruz:
      email: none
      logged_in: false
      name: Isabelle
      password: ISA020564
    tokiwooki:
      email: none
      logged_in: false
      name: Caroline
      password: schwabl
preauthorized:
  emails: []
